
export enum HttpErrorCodes {
    UNKOWN_ERROR = "UNKNOWN_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    CONFLICT_ERROR = "CONFLICT_ERROR",
    NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
    USER_BLOCKED_ERROR = "USER_BLOCKED_ERROR",
    USER_DISABLED_ERROR = "USER_DISABLED_ERROR",
    USER_UNVERIFYED_ERROR = "USER_UNVERIFYED_ERROR",
    PASSWORD_DONT_MATCHES = "PASSWORD_DONT_MATCHES",
    UNLOGGED_ERROR = "UNLOGGED_ERRROR",
    SESSION_EXPIRED_ERROR = "SESSION_EXPIRED_ERROR",
    UNAUTHORIZED_ERROR = "UNAUTHORIZED",
    REVOKED_TOKEN_ERROR = "REVOKED_TOKEN_ERROR"
}