/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicConfirmRouteImport } from './routes/_public/confirm'
import { Route as PublicResendConfirmationRouteImport } from './routes/_public/resend-confirmation'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConfirmRoute = PublicConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResendConfirmationRoute =
  PublicResendConfirmationRouteImport.update({
    id: '/resend-confirmation',
    path: '/resend-confirmation',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/confirm': typeof PublicConfirmRoute
  '/resend-confirmation': typeof PublicResendConfirmationRoute
  '/signup': typeof PublicSignupRoute
}
export interface FileRoutesByTo {
  '/confirm': typeof PublicConfirmRoute
  '/resend-confirmation': typeof PublicResendConfirmationRoute
  '/signup': typeof PublicSignupRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/confirm': typeof PublicConfirmRoute
  '/_public/resend-confirmation': typeof PublicResendConfirmationRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confirm' | '/resend-confirmation' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/confirm' | '/resend-confirmation' | '/signup' | '/'
  id:
    | '__root__'
    | '/_public'
    | '/_public/confirm'
    | '/_public/resend-confirmation'
    | '/_public/signup'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/confirm': {
      id: '/_public/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof PublicConfirmRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/resend-confirmation': {
      id: '/_public/resend-confirmation'
      path: '/resend-confirmation'
      fullPath: '/resend-confirmation'
      preLoaderRoute: typeof PublicResendConfirmationRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicConfirmRoute: typeof PublicConfirmRoute
  PublicResendConfirmationRoute: typeof PublicResendConfirmationRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicConfirmRoute: PublicConfirmRoute,
  PublicResendConfirmationRoute: PublicResendConfirmationRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
